#ifndef _ARMADA3700_UTMI_H
#define _ARMADA3700_UTMI_H

enum a3700_utmi_phy_id {
	A3700_UTMI_USB2_PHY = 0,
	A3700_UTMI_USB32_PHY,
	A3700_UTMI_PHY_MAX,
};

#define PLL_LOCK_TIMEOUT		1000

#define USB2_PHY_PLL_CTRL_REG0		0x0
#define PLL_REF_DIV_OFF			(0)
#define PLL_REF_DIV_MASK		(0x7F << PLL_REF_DIV_OFF)
#define PLL_REF_DIV_5			(0x5)
#define PLL_FB_DIV_OFF			(16)
#define PLL_FB_DIV_MASK			(0x1FF << PLL_FB_DIV_OFF)
#define PLL_FB_DIV_96			(96)
#define PLL_SEL_LPFR_OFF		(28)
#define PLL_SEL_LPFR_MASK		(0x3 << PLL_SEL_LPFR_OFF)
#define PLL_READY			BIT(31)

#define USB2_PHY2_CTRL_ADDR		(0x804)
#define USB2_PHY2_SUSPM			BIT(7)
#define USB2_PHY2_PU			BIT(0)

#define USB2_PHY2_PLL_CTRL0_ADDR	(0x0)

/* Both UTMI PHY and UTMI OTG PHY */
#define USB2_PHY_CAL_CTRL_ADDR		(0x8)
#define PHY_PLLCAL_DONE			BIT(31)
#define PHY_IMPCAL_DONE			BIT(23)
#define USB2_PHY_OTG_CTRL_ADDR		(0x34)
#define PHY_PU_OTG			BIT(4)
#define USB2_RX_CHAN_CTRL1_ADDR		(0x18)
#define USB2PHY_SQCAL_DONE		BIT(31)

#define USB2_PHY_CHRGR_DET_ADDR		(0x38)
#define PHY_CDP_EN			BIT(2)
#define PHY_DCP_EN			BIT(3)
#define PHY_PD_EN			BIT(4)
#define PHY_PU_CHRG_DTC			BIT(5)
#define PHY_CDP_DM_AUTO			BIT(7)
#define PHY_ENSWITCH_DP			BIT(12)
#define PHY_ENSWITCH_DM			BIT(13)

#define USB2_OTG_PHY_CTRL_ADDR		(0x820)
#define USB2_OTGPHY2_SUSPM		BIT(14)
#define USB2_OTGPHY2_PU			BIT(0)
#define USB2_DP_PULLDN_DEV_MODE		BIT(5)
#define USB2_DM_PULLDN_DEV_MODE		BIT(6)

#define USB2_PHY_CTRL_ADDR(usb32) (usb32 == 0 ? USB2_PHY2_CTRL_ADDR : USB2_OTG_PHY_CTRL_ADDR)
#define RB_USB2PHY_SUSPM(usb32) (usb32 == 0 ? USB2_PHY2_SUSPM : USB2_OTGPHY2_SUSPM)
#define RB_USB2PHY_PU(usb32) (usb32 == 0 ? USB2_PHY2_PU : USB2_OTGPHY2_PU)

#endif /* _ARMADA3700_UTMI_H */
