# SPDX-License-Identifier: GPL-2.0
obj-y           += octeontx2-sdp/
obj-y 		+= hw-access/
obj-y		+= octeontx2-dpi/
obj-$(CONFIG_MVMDIO_UIO) += mvmdio_uio.o
obj-$(CONFIG_MARVELL_CN10K_SERDES_DIAGNOSTICS) += cn10k_serdes_diag.o
obj-$(CONFIG_MRVL_PHY_DIAGNOSTICS) += phy_diag.o
obj-y		+= ptm-ep/
