# SPDX-License-Identifier: GPL-2.0
# Berlin SoC Family
dtb-$(CONFIG_ARCH_BERLIN) += berlin4ct-dmp.dtb
dtb-$(CONFIG_ARCH_BERLIN) += berlin4ct-stb.dtb

# Mvebu SoC Family
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-db-B.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-db-C.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-espressobin.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db-B.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db-C.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db-D.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db-E.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-db-B.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-db-C.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-db-D.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-db-E.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-mcbin.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-mcbin-single-shot.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8080-pd.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8082-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8082-db-B.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8084-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8160-pd.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8162-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8164-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8320-pd.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
