# Berlin SoC Family
dtb-$(CONFIG_ARCH_BERLIN) += berlin4ct-dmp.dtb
dtb-$(CONFIG_ARCH_BERLIN) += berlin4ct-stb.dtb

# Mvebu SoC Family
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-db-B.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-db-C.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-community.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-37x0-customer.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3900-db-axis.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3900-db-vd.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db-B.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db-C.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db-D.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db-E.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db-nand.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db-all-pcie.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7020-amc.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-70x0-customer.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-pcac.dtb
dtb-$(CONFIG_ARCH_MVEBU_PD) += armada-7040-pd.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db-pp2-vanilla.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-db-pp2-vanilla.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-mcbin-pp2-vanilla.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-db-B.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-db-C.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-db-D.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-db-E.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-mcbin.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-ocp.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-80x0-customer.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
