/*******************************************************************************
Copyright (C) Marvell International Ltd. and its affiliates

This software file (the "File") is owned and distributed by Marvell
International Ltd. and/or its affiliates ("Marvell") under the following
alternative licensing terms.  Once you have made an election to distribute the
File under one of the following license alternatives, please (i) delete this
introductory statement regarding license alternatives, (ii) delete the two
license alternatives that you have not elected to use and (iii) preserve the
Marvell copyright notice above.


********************************************************************************
Marvell GPL License Option

If you received this File from Marvell, you may opt to use, redistribute and/or
modify this File in accordance with the terms and conditions of the General
Public License Version 2, June 1991 (the "GPL License"), a copy of which is
available along with the File in the license.txt file or by writing to the Free
Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 or
on the worldwide web at http://www.gnu.org/licenses/gpl.txt.

THE FILE IS DISTRIBUTED AS-IS, WITHOUT WARRANTY OF ANY KIND, AND THE IMPLIED
WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY
DISCLAIMED.  The GPL License provides additional details about this warranty
disclaimer.
*******************************************************************************/
#ifndef __mv_gmac_regs_h__
#define __mv_gmac_regs_h__

/* includes */

/* unit offset */
#define MV_GMAC_UNIT_OFFSET		0x03000000

/* Port Mac Control0 */
#define MV_GMAC_PORT_CTRL0_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x0000 + (port) * 0x1000)
#define MV_GMAC_PORT_CTRL0_PORTEN_OFFS		0
#define MV_GMAC_PORT_CTRL0_PORTEN_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL0_PORTEN_OFFS)

#define MV_GMAC_PORT_CTRL0_PORTTYPE_OFFS		1
#define MV_GMAC_PORT_CTRL0_PORTTYPE_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL0_PORTTYPE_OFFS)

#define MV_GMAC_PORT_CTRL0_FRAMESIZELIMIT_OFFS		2
#define MV_GMAC_PORT_CTRL0_FRAMESIZELIMIT_MASK    \
		(0x00001fff << MV_GMAC_PORT_CTRL0_FRAMESIZELIMIT_OFFS)

#define MV_GMAC_PORT_CTRL0_COUNT_EN_OFFS		15
#define MV_GMAC_PORT_CTRL0_COUNT_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL0_COUNT_EN_OFFS)


/* Port Mac Control1 */
#define MV_GMAC_PORT_CTRL1_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x0004 + (port) * 0x1000)
#define MV_GMAC_PORT_CTRL1_EN_RX_CRC_CHECK_OFFS	0
#define MV_GMAC_PORT_CTRL1_EN_RX_CRC_CHECK_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL1_EN_RX_CRC_CHECK_OFFS)

#define MV_GMAC_PORT_CTRL1_EN_PERIODIC_FC_XON_OFFS		1
#define MV_GMAC_PORT_CTRL1_EN_PERIODIC_FC_XON_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL1_EN_PERIODIC_FC_XON_OFFS)

#define MV_GMAC_PORT_CTRL1_MGMII_MODE_OFFS		2
#define MV_GMAC_PORT_CTRL1_MGMII_MODE_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL1_MGMII_MODE_OFFS)

#define MV_GMAC_PORT_CTRL1_PFC_CASCADE_PORT_ENABLE_OFFS		3
#define MV_GMAC_PORT_CTRL1_PFC_CASCADE_PORT_ENABLE_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL1_PFC_CASCADE_PORT_ENABLE_OFFS)

#define MV_GMAC_PORT_CTRL1_DIS_EXCESSIVE_COL_OFFS		4
#define MV_GMAC_PORT_CTRL1_DIS_EXCESSIVE_COL_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL1_DIS_EXCESSIVE_COL_OFFS)

#define MV_GMAC_PORT_CTRL1_GMII_LOOPBACK_OFFS		5
#define MV_GMAC_PORT_CTRL1_GMII_LOOPBACK_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL1_GMII_LOOPBACK_OFFS)

#define MV_GMAC_PORT_CTRL1_PCS_LOOPBACK_OFFS		6
#define MV_GMAC_PORT_CTRL1_PCS_LOOPBACK_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL1_PCS_LOOPBACK_OFFS)

#define MV_GMAC_PORT_CTRL1_FC_SA_ADDR_LO_OFFS		7
#define MV_GMAC_PORT_CTRL1_FC_SA_ADDR_LO_MASK    \
		(0x000000ff << MV_GMAC_PORT_CTRL1_FC_SA_ADDR_LO_OFFS)

#define MV_GMAC_PORT_CTRL1_EN_SHORT_PREAMBLE_OFFS		15
#define MV_GMAC_PORT_CTRL1_EN_SHORT_PREAMBLE_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL1_EN_SHORT_PREAMBLE_OFFS)


/* Port Mac Control2 */
#define MV_GMAC_PORT_CTRL2_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x0008 + (port) * 0x1000)
#define MV_GMAC_PORT_CTRL2_SGMII_MODE_OFFS		0
#define MV_GMAC_PORT_CTRL2_SGMII_MODE_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL2_SGMII_MODE_OFFS)

#define MV_GMAC_PORT_CTRL2_FC_MODE_OFFS		1
#define MV_GMAC_PORT_CTRL2_FC_MODE_MASK    \
		(0x00000003 << MV_GMAC_PORT_CTRL2_FC_MODE_OFFS)

#define MV_GMAC_PORT_CTRL2_PCS_EN_OFFS		3
#define MV_GMAC_PORT_CTRL2_PCS_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL2_PCS_EN_OFFS)

#define MV_GMAC_PORT_CTRL2_RGMII_MODE_OFFS		4
#define MV_GMAC_PORT_CTRL2_RGMII_MODE_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL2_RGMII_MODE_OFFS)

#define MV_GMAC_PORT_CTRL2_DIS_PADING_OFFS		5
#define MV_GMAC_PORT_CTRL2_DIS_PADING_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL2_DIS_PADING_OFFS)

#define MV_GMAC_PORT_CTRL2_PORTMACRESET_OFFS		6
#define MV_GMAC_PORT_CTRL2_PORTMACRESET_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL2_PORTMACRESET_OFFS)

#define MV_GMAC_PORT_CTRL2_TX_DRAIN_OFFS		7
#define MV_GMAC_PORT_CTRL2_TX_DRAIN_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL2_TX_DRAIN_OFFS)

#define MV_GMAC_PORT_CTRL2_EN_MII_ODD_PRE_OFFS		8
#define MV_GMAC_PORT_CTRL2_EN_MII_ODD_PRE_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL2_EN_MII_ODD_PRE_OFFS)

#define MV_GMAC_PORT_CTRL2_CLK_125_BYPS_EN_OFFS		9
#define MV_GMAC_PORT_CTRL2_CLK_125_BYPS_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL2_CLK_125_BYPS_EN_OFFS)

#define MV_GMAC_PORT_CTRL2_PRBS_CHECK_EN_OFFS		10
#define MV_GMAC_PORT_CTRL2_PRBS_CHECK_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL2_PRBS_CHECK_EN_OFFS)

#define MV_GMAC_PORT_CTRL2_PRBS_GEN_EN_OFFS		11
#define MV_GMAC_PORT_CTRL2_PRBS_GEN_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL2_PRBS_GEN_EN_OFFS)

#define MV_GMAC_PORT_CTRL2_SELECT_DATA_TO_TX_OFFS		12
#define MV_GMAC_PORT_CTRL2_SELECT_DATA_TO_TX_MASK    \
		(0x00000003 << MV_GMAC_PORT_CTRL2_SELECT_DATA_TO_TX_OFFS)

#define MV_GMAC_PORT_CTRL2_EN_COL_ON_BP_OFFS		14
#define MV_GMAC_PORT_CTRL2_EN_COL_ON_BP_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL2_EN_COL_ON_BP_OFFS)

#define MV_GMAC_PORT_CTRL2_EARLY_REJECT_MODE_OFFS		15
#define MV_GMAC_PORT_CTRL2_EARLY_REJECT_MODE_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL2_EARLY_REJECT_MODE_OFFS)


/* Port Auto-negotiation Configuration */
#define MV_GMAC_PORT_AUTO_NEG_CFG_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x000c + (port) * 0x1000)
#define MV_GMAC_PORT_AUTO_NEG_CFG_FORCE_LINK_DOWN_OFFS		0
#define MV_GMAC_PORT_AUTO_NEG_CFG_FORCE_LINK_DOWN_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_FORCE_LINK_DOWN_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_FORCE_LINK_UP_OFFS		1
#define MV_GMAC_PORT_AUTO_NEG_CFG_FORCE_LINK_UP_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_FORCE_LINK_UP_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_EN_PCS_AN_OFFS		2
#define MV_GMAC_PORT_AUTO_NEG_CFG_EN_PCS_AN_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_EN_PCS_AN_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_AN_BYPASS_EN_OFFS		3
#define MV_GMAC_PORT_AUTO_NEG_CFG_AN_BYPASS_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_AN_BYPASS_EN_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_INBAND_RESTARTAN_OFFS		4
#define MV_GMAC_PORT_AUTO_NEG_CFG_INBAND_RESTARTAN_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_INBAND_RESTARTAN_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_SET_MII_SPEED_OFFS		5
#define MV_GMAC_PORT_AUTO_NEG_CFG_SET_MII_SPEED_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_SET_MII_SPEED_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_SET_GMII_SPEED_OFFS		6
#define MV_GMAC_PORT_AUTO_NEG_CFG_SET_GMII_SPEED_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_SET_GMII_SPEED_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_EN_AN_SPEED_OFFS		7
#define MV_GMAC_PORT_AUTO_NEG_CFG_EN_AN_SPEED_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_EN_AN_SPEED_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_ADV_PAUSE_OFFS		9
#define MV_GMAC_PORT_AUTO_NEG_CFG_ADV_PAUSE_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_ADV_PAUSE_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_ADV_ASM_PAUSE_OFFS		10
#define MV_GMAC_PORT_AUTO_NEG_CFG_ADV_ASM_PAUSE_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_ADV_ASM_PAUSE_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_EN_FC_AN_OFFS			11
#define MV_GMAC_PORT_AUTO_NEG_CFG_EN_FC_AN_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_EN_FC_AN_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_SET_FULL_DX_OFFS		12
#define MV_GMAC_PORT_AUTO_NEG_CFG_SET_FULL_DX_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_SET_FULL_DX_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_EN_FDX_AN_OFFS		13
#define MV_GMAC_PORT_AUTO_NEG_CFG_EN_FDX_AN_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_EN_FDX_AN_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_PHY_MODE_OFFS		14
#define MV_GMAC_PORT_AUTO_NEG_CFG_PHY_MODE_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_PHY_MODE_OFFS)

#define MV_GMAC_PORT_AUTO_NEG_CFG_CHOOSE_SAMPLE_TX_CONFIG_OFFS		15
#define MV_GMAC_PORT_AUTO_NEG_CFG_CHOOSE_SAMPLE_TX_CONFIG_MASK    \
		(0x00000001 << MV_GMAC_PORT_AUTO_NEG_CFG_CHOOSE_SAMPLE_TX_CONFIG_OFFS)


/* Port Status0 */
#define MV_GMAC_PORT_STATUS0_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x0010 + (port) * 0x1000)
#define MV_GMAC_PORT_STATUS0_LINKUP_OFFS		0
#define MV_GMAC_PORT_STATUS0_LINKUP_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_LINKUP_OFFS)

#define MV_GMAC_PORT_STATUS0_GMIISPEED_OFFS		1
#define MV_GMAC_PORT_STATUS0_GMIISPEED_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_GMIISPEED_OFFS)

#define MV_GMAC_PORT_STATUS0_MIISPEED_OFFS		2
#define MV_GMAC_PORT_STATUS0_MIISPEED_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_MIISPEED_OFFS)

#define MV_GMAC_PORT_STATUS0_FULLDX_OFFS		3
#define MV_GMAC_PORT_STATUS0_FULLDX_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_FULLDX_OFFS)

#define MV_GMAC_PORT_STATUS0_RXFCEN_OFFS		4
#define MV_GMAC_PORT_STATUS0_RXFCEN_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_RXFCEN_OFFS)

#define MV_GMAC_PORT_STATUS0_TXFCEN_OFFS		5
#define MV_GMAC_PORT_STATUS0_TXFCEN_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_TXFCEN_OFFS)

#define MV_GMAC_PORT_STATUS0_PORTRXPAUSE_OFFS		6
#define MV_GMAC_PORT_STATUS0_PORTRXPAUSE_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_PORTRXPAUSE_OFFS)

#define MV_GMAC_PORT_STATUS0_PORTTXPAUSE_OFFS		7
#define MV_GMAC_PORT_STATUS0_PORTTXPAUSE_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_PORTTXPAUSE_OFFS)

#define MV_GMAC_PORT_STATUS0_PORTIS_DOINGPRESSURE_OFFS		8
#define MV_GMAC_PORT_STATUS0_PORTIS_DOINGPRESSURE_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_PORTIS_DOINGPRESSURE_OFFS)

#define MV_GMAC_PORT_STATUS0_PORTBUFFULL_OFFS		9
#define MV_GMAC_PORT_STATUS0_PORTBUFFULL_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_PORTBUFFULL_OFFS)

#define MV_GMAC_PORT_STATUS0_SYNCFAIL10MS_OFFS		10
#define MV_GMAC_PORT_STATUS0_SYNCFAIL10MS_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_SYNCFAIL10MS_OFFS)

#define MV_GMAC_PORT_STATUS0_ANDONE_OFFS		11
#define MV_GMAC_PORT_STATUS0_ANDONE_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_ANDONE_OFFS)

#define MV_GMAC_PORT_STATUS0_INBAND_AUTONEG_BYPASSACT_OFFS		12
#define MV_GMAC_PORT_STATUS0_INBAND_AUTONEG_BYPASSACT_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_INBAND_AUTONEG_BYPASSACT_OFFS)

#define MV_GMAC_PORT_STATUS0_SERDESPLL_LOCKED_OFFS		13
#define MV_GMAC_PORT_STATUS0_SERDESPLL_LOCKED_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_SERDESPLL_LOCKED_OFFS)

#define MV_GMAC_PORT_STATUS0_SYNCOK_OFFS		14
#define MV_GMAC_PORT_STATUS0_SYNCOK_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_SYNCOK_OFFS)

#define MV_GMAC_PORT_STATUS0_SQUELCHNOT_DETECTED_OFFS		15
#define MV_GMAC_PORT_STATUS0_SQUELCHNOT_DETECTED_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS0_SQUELCHNOT_DETECTED_OFFS)


/* Port Serial Parameters Configuration */
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x0014 + (port) * 0x1000)
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_UNIDIRECTIONAL_ENABLE_OFFS	0
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_UNIDIRECTIONAL_ENABLE_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_CFG_UNIDIRECTIONAL_ENABLE_OFFS)

#define MV_GMAC_PORT_SERIAL_PARAM_CFG_RETRANSMIT_COLLISION_DOMAIN_OFFS		1
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_RETRANSMIT_COLLISION_DOMAIN_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_CFG_RETRANSMIT_COLLISION_DOMAIN_OFFS)

#define MV_GMAC_PORT_SERIAL_PARAM_CFG_PUMA2_BTS1444_EN_OFFS		2
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_PUMA2_BTS1444_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_CFG_PUMA2_BTS1444_EN_OFFS)

#define MV_GMAC_PORT_SERIAL_PARAM_CFG_FORWARD_802_3X_FC_EN_OFFS		3
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_FORWARD_802_3X_FC_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_CFG_FORWARD_802_3X_FC_EN_OFFS)

#define MV_GMAC_PORT_SERIAL_PARAM_CFG_BP_EN_OFFS		4
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_BP_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_CFG_BP_EN_OFFS)

#define MV_GMAC_PORT_SERIAL_PARAM_CFG_RX_NEGEDGE_SAMPLE_EN_OFFS		5
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_RX_NEGEDGE_SAMPLE_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_CFG_RX_NEGEDGE_SAMPLE_EN_OFFS)

#define MV_GMAC_PORT_SERIAL_PARAM_CFG_COL_DOMAIN_LIMIT_OFFS		6
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_COL_DOMAIN_LIMIT_MASK    \
		(0x0000003f << MV_GMAC_PORT_SERIAL_PARAM_CFG_COL_DOMAIN_LIMIT_OFFS)

#define MV_GMAC_PORT_SERIAL_PARAM_CFG_PERIODIC_TYPE_SELECT_OFFS		12
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_PERIODIC_TYPE_SELECT_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_CFG_PERIODIC_TYPE_SELECT_OFFS)

#define MV_GMAC_PORT_SERIAL_PARAM_CFG_PER_PRIORITY_FC_EN_OFFS		13
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_PER_PRIORITY_FC_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_CFG_PER_PRIORITY_FC_EN_OFFS)

#define MV_GMAC_PORT_SERIAL_PARAM_CFG_TX_STANDARD_PRBS7_OFFS		14
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_TX_STANDARD_PRBS7_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_CFG_TX_STANDARD_PRBS7_OFFS)

#define MV_GMAC_PORT_SERIAL_PARAM_CFG_REVERSE_PRBS_RX_OFFS		15
#define MV_GMAC_PORT_SERIAL_PARAM_CFG_REVERSE_PRBS_RX_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_CFG_REVERSE_PRBS_RX_OFFS)


/* Port Fifo Configuration 0 */
#define MV_GMAC_PORT_FIFO_CFG_0_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x0018 + (port) * 0x1000)
#define MV_GMAC_PORT_FIFO_CFG_0_TX_FIFO_HIGH_WM_OFFS		0
#define MV_GMAC_PORT_FIFO_CFG_0_TX_FIFO_HIGH_WM_MASK    \
		(0x000000ff << MV_GMAC_PORT_FIFO_CFG_0_TX_FIFO_HIGH_WM_OFFS)

#define MV_GMAC_PORT_FIFO_CFG_0_TX_FIFO_LOW_WM_OFFS		8
#define MV_GMAC_PORT_FIFO_CFG_0_TX_FIFO_LOW_WM_MASK    \
		(0x000000ff << MV_GMAC_PORT_FIFO_CFG_0_TX_FIFO_LOW_WM_OFFS)


/* Port Fifo Configuration 1 */
#define MV_GMAC_PORT_FIFO_CFG_1_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x001c + (port) * 0x1000)
#define MV_GMAC_PORT_FIFO_CFG_1_RX_FIFO_MAX_TH_OFFS		0
#define MV_GMAC_PORT_FIFO_CFG_1_RX_FIFO_MAX_TH_MASK    \
		(0x0000003f << MV_GMAC_PORT_FIFO_CFG_1_RX_FIFO_MAX_TH_OFFS)

#define MV_GMAC_PORT_FIFO_CFG_1_TX_FIFO_MIN_TH_OFFS		6
#define MV_GMAC_PORT_FIFO_CFG_1_TX_FIFO_MIN_TH_MASK    \
		(0x000000ff << MV_GMAC_PORT_FIFO_CFG_1_TX_FIFO_MIN_TH_OFFS)

#define MV_GMAC_PORT_FIFO_CFG_1_PORT_EN_FIX_EN_OFFS		15
#define MV_GMAC_PORT_FIFO_CFG_1_PORT_EN_FIX_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_FIFO_CFG_1_PORT_EN_FIX_EN_OFFS)


/* Port Serdes Configuration0 */
#define MV_GMAC_PORT_SERDES_CFG0_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x0028 + (port) * 0x1000)
#define MV_GMAC_PORT_SERDES_CFG0_SERDESRESET_OFFS		0
#define MV_GMAC_PORT_SERDES_CFG0_SERDESRESET_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_SERDESRESET_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_PU_TX_OFFS		1
#define MV_GMAC_PORT_SERDES_CFG0_PU_TX_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_PU_TX_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_PU_RX_OFFS		2
#define MV_GMAC_PORT_SERDES_CFG0_PU_RX_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_PU_RX_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_PU_PLL_OFFS		3
#define MV_GMAC_PORT_SERDES_CFG0_PU_PLL_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_PU_PLL_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_PU_IVREF_OFFS		4
#define MV_GMAC_PORT_SERDES_CFG0_PU_IVREF_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_PU_IVREF_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_TESTEN_OFFS		5
#define MV_GMAC_PORT_SERDES_CFG0_TESTEN_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_TESTEN_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_DPHER_EN_OFFS		6
#define MV_GMAC_PORT_SERDES_CFG0_DPHER_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_DPHER_EN_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_RUDI_INVALID_ENABLE_OFFS		7
#define MV_GMAC_PORT_SERDES_CFG0_RUDI_INVALID_ENABLE_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_RUDI_INVALID_ENABLE_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_ACK_OVERRIDE_ENABLE_OFFS		8
#define MV_GMAC_PORT_SERDES_CFG0_ACK_OVERRIDE_ENABLE_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_ACK_OVERRIDE_ENABLE_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_CONFIG_WORD_ENABLE_OFFS		9
#define MV_GMAC_PORT_SERDES_CFG0_CONFIG_WORD_ENABLE_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_CONFIG_WORD_ENABLE_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_SYNC_FAIL_INT_ENABLE_OFFS		10
#define MV_GMAC_PORT_SERDES_CFG0_SYNC_FAIL_INT_ENABLE_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_SYNC_FAIL_INT_ENABLE_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_MASTER_MODE_ENABLE_OFFS		11
#define MV_GMAC_PORT_SERDES_CFG0_MASTER_MODE_ENABLE_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_MASTER_MODE_ENABLE_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_TERM75_TX_OFFS		12
#define MV_GMAC_PORT_SERDES_CFG0_TERM75_TX_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_TERM75_TX_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_OUTAMP_OFFS		13
#define MV_GMAC_PORT_SERDES_CFG0_OUTAMP_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_OUTAMP_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_BTS712_FIX_EN_OFFS		14
#define MV_GMAC_PORT_SERDES_CFG0_BTS712_FIX_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_BTS712_FIX_EN_OFFS)

#define MV_GMAC_PORT_SERDES_CFG0_BTS156_FIX_EN_OFFS		15
#define MV_GMAC_PORT_SERDES_CFG0_BTS156_FIX_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERDES_CFG0_BTS156_FIX_EN_OFFS)


/* Port Serdes Configuration1 */
#define MV_GMAC_PORT_SERDES_CFG1_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x002c + (port) * 0x1000)
#define MV_GMAC_PORT_SERDES_CFG1_SMII_RX_10MB_CLK_EDGE_SEL_OFFS	0
#define MV_GMAC_PORT_SERDES_CFG1_SMII_RX_10MB_CLK_EDGE_SEL_MASK    \
		(0x00000001 << MV_GMAC_GMAC_PORT_SERDES_CFG1_SMII_RX_10MB_CLK_EDGE_SEL_OFFS)

#define MV_GMAC_GMAC_PORT_SERDES_CFG1_SMII_TX_10MB_CLK_EDGE_SEL_OFFS	1
#define MV_GMAC_GMAC_PORT_SERDES_CFG1_SMII_TX_10MB_CLK_EDGE_SEL_MASK    \
		(0x00000001 << MV_GMAC_GMAC_PORT_SERDES_CFG1_SMII_TX_10MB_CLK_EDGE_SEL_OFFS)

#define MV_GMAC_GMAC_PORT_SERDES_CFG1_MEN_OFFS		2
#define MV_GMAC_GMAC_PORT_SERDES_CFG1_MEN_MASK    \
		(0x00000003 << MV_GMAC_GMAC_PORT_SERDES_CFG1_MEN_OFFS)

#define MV_GMAC_GMAC_PORT_SERDES_CFG1_VCMS_OFFS		4
#define MV_GMAC_GMAC_PORT_SERDES_CFG1_VCMS_MASK    \
		(0x00000001 << MV_GMAC_GMAC_PORT_SERDES_CFG1_VCMS_OFFS)

#define MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_USE_SIGDET_OFFS		5
#define MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_USE_SIGDET_MASK    \
		(0x00000001 << MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_USE_SIGDET_OFFS)

#define MV_GMAC_GMAC_PORT_SERDES_CFG1_EN_CRS_MASK_TX_OFFS		6
#define MV_GMAC_GMAC_PORT_SERDES_CFG1_EN_CRS_MASK_TX_MASK    \
		(0x00000001 << MV_GMAC_GMAC_PORT_SERDES_CFG1_EN_CRS_MASK_TX_OFFS)

#define MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_ENABLE_OFFS		7
#define MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_ENABLE_MASK    \
		(0x00000001 << MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_ENABLE_OFFS)

#define MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_PHY_ADDRESS_OFFS		8
#define MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_PHY_ADDRESS_MASK    \
		(0x0000001f << MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_PHY_ADDRESS_OFFS)

#define MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_SIGDET_POLARITY_OFFS		13
#define MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_SIGDET_POLARITY_MASK    \
		(0x00000001 << MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_SIGDET_POLARITY_OFFS)

#define MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_INTERRUPT_POLARITY_OFFS		14
#define MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_INTERRUPT_POLARITY_MASK    \
		(0x00000001 << MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_INTERRUPT_POLARITY_OFFS)

#define MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_SERDES_POLARITY_OFFS		15
#define MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_SERDES_POLARITY_MASK    \
		(0x00000001 << MV_GMAC_GMAC_PORT_SERDES_CFG1_100FX_PCS_SERDES_POLARITY_OFFS)


/* Port Serdes Configuration2 */
#define MV_GMAC_PORT_SERDES_CFG2_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x0030 + (port) * 0x1000)
#define MV_GMAC_PORT_SERDES_CFG2_AN_ADV_CONFIGURATION_OFFS	0
#define MV_GMAC_PORT_SERDES_CFG2_AN_ADV_CONFIGURATION_MASK    \
		(0x0000ffff << MV_GMAC_PORT_SERDES_CFG2_AN_ADV_CONFIGURATION_OFFS)


/* Port Serdes Configuration3 */
#define MV_GMAC_PORT_SERDES_CFG3_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x0034 + (port) * 0x1000)
#define MV_GMAC_PORT_SERDES_CFG3_ABILITY_MATCH_STATUS_OFFS		0
#define MV_GMAC_PORT_SERDES_CFG3_ABILITY_MATCH_STATUS_MASK    \
		(0x0000ffff << MV_GMAC_PORT_SERDES_CFG3_ABILITY_MATCH_STATUS_OFFS)


/* Port Prbs Status */
#define MV_GMAC_PORT_PRBS_STATUS_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x0038 + (port) * 0x1000)
#define MV_GMAC_PORT_PRBS_STATUS_PRBSCHECK_LOCKED_OFFS		0
#define MV_GMAC_PORT_PRBS_STATUS_PRBSCHECK_LOCKED_MASK    \
		(0x00000001 << MV_GMAC_PORT_PRBS_STATUS_PRBSCHECK_LOCKED_OFFS)

#define MV_GMAC_PORT_PRBS_STATUS_PRBSCHECKRDY_OFFS		1
#define MV_GMAC_PORT_PRBS_STATUS_PRBSCHECKRDY_MASK    \
		(0x00000001 << MV_GMAC_PORT_PRBS_STATUS_PRBSCHECKRDY_OFFS)


/* Port Prbs Error Counter */
#define MV_GMAC_PORT_PRBS_ERR_CNTR_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x003c + (port) * 0x1000)
#define MV_GMAC_PORT_PRBS_ERR_CNTR_PRBSBITERRCNT_OFFS		0
#define MV_GMAC_PORT_PRBS_ERR_CNTR_PRBSBITERRCNT_MASK    \
		(0x0000ffff << MV_GMAC_PORT_PRBS_ERR_CNTR_PRBSBITERRCNT_OFFS)


/* Port Status1 */
#define MV_GMAC_PORT_STATUS1_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x0040 + (port) * 0x1000)
#define MV_GMAC_PORT_STATUS1_MEDIAACTIVE_OFFS		0
#define MV_GMAC_PORT_STATUS1_MEDIAACTIVE_MASK    \
		(0x00000001 << MV_GMAC_PORT_STATUS1_MEDIAACTIVE_OFFS)


/* Port Mib Counters Control */
#define MV_GMAC_PORT_MIB_CNTRS_CTRL_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x0044 + (port) * 0x1000)
#define MV_GMAC_PORT_MIB_CNTRS_CTRL_MIB_COPY_TRIGGER_OFFS	0
#define MV_GMAC_PORT_MIB_CNTRS_CTRL_MIB_COPY_TRIGGER_MASK    \
		(0x00000001 << MV_GMAC_PORT_MIB_CNTRS_CTRL_MIB_COPY_TRIGGER_OFFS)

#define MV_GMAC_PORT_MIB_CNTRS_CTRL_MIB_CLEAR_ON_READ__OFFS		1
#define MV_GMAC_PORT_MIB_CNTRS_CTRL_MIB_CLEAR_ON_READ__MASK    \
		(0x00000001 << MV_GMAC_PORT_MIB_CNTRS_CTRL_MIB_CLEAR_ON_READ__OFFS)

#define MV_GMAC_PORT_MIB_CNTRS_CTRL_RX_HISTOGRAM_EN_OFFS		2
#define MV_GMAC_PORT_MIB_CNTRS_CTRL_RX_HISTOGRAM_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_MIB_CNTRS_CTRL_RX_HISTOGRAM_EN_OFFS)

#define MV_GMAC_PORT_MIB_CNTRS_CTRL_TX_HISTOGRAM_EN_OFFS		3
#define MV_GMAC_PORT_MIB_CNTRS_CTRL_TX_HISTOGRAM_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_MIB_CNTRS_CTRL_TX_HISTOGRAM_EN_OFFS)

#define MV_GMAC_PORT_MIB_CNTRS_CTRL_MFA1_BTT940_FIX_ENABLE__OFFS		4
#define MV_GMAC_PORT_MIB_CNTRS_CTRL_MFA1_BTT940_FIX_ENABLE__MASK    \
		(0x00000001 << MV_GMAC_PORT_MIB_CNTRS_CTRL_MFA1_BTT940_FIX_ENABLE__OFFS)

#define MV_GMAC_PORT_MIB_CNTRS_CTRL_XCAT_BTS_340_EN__OFFS		5
#define MV_GMAC_PORT_MIB_CNTRS_CTRL_XCAT_BTS_340_EN__MASK    \
		(0x00000001 << MV_GMAC_PORT_MIB_CNTRS_CTRL_XCAT_BTS_340_EN__OFFS)

#define MV_GMAC_PORT_MIB_CNTRS_CTRL_MIB_4_COUNT_HIST_OFFS		6
#define MV_GMAC_PORT_MIB_CNTRS_CTRL_MIB_4_COUNT_HIST_MASK    \
		(0x00000001 << MV_GMAC_PORT_MIB_CNTRS_CTRL_MIB_4_COUNT_HIST_OFFS)

#define MV_GMAC_PORT_MIB_CNTRS_CTRL_MIB_4_LIMIT_1518_1522_OFFS		7
#define MV_GMAC_PORT_MIB_CNTRS_CTRL_MIB_4_LIMIT_1518_1522_MASK    \
		(0x00000001 << MV_GMAC_PORT_MIB_CNTRS_CTRL_MIB_4_LIMIT_1518_1522_OFFS)


/* Port Mac Control3 */
#define MV_GMAC_PORT_CTRL3_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x0048 + (port) * 0x1000)
#define MV_GMAC_PORT_CTRL3_BUF_SIZE_OFFS		0
#define MV_GMAC_PORT_CTRL3_BUF_SIZE_MASK    \
		(0x0000003f << MV_GMAC_PORT_CTRL3_BUF_SIZE_OFFS)

#define MV_GMAC_PORT_CTRL3_IPG_DATA_OFFS		6
#define MV_GMAC_PORT_CTRL3_IPG_DATA_MASK    \
		(0x000001ff << MV_GMAC_PORT_CTRL3_IPG_DATA_OFFS)

#define MV_GMAC_PORT_CTRL3_LLFC_GLOBAL_FC_ENABLE_OFFS		15
#define MV_GMAC_PORT_CTRL3_LLFC_GLOBAL_FC_ENABLE_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL3_LLFC_GLOBAL_FC_ENABLE_OFFS)


/* QSGMII */
#define MV_GMAC_QSGMII_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x004c + (port) * 0x1000)
#define MV_GMAC_QSGMII_QSGMII_REG_OFFS		0
#define MV_GMAC_QSGMII_QSGMII_REG_MASK    \
		(0x0000ffff << MV_GMAC_QSGMII_QSGMII_REG_OFFS)


/* Qsgmii Status */
#define MV_GMAC_QSGMII_STATUS_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x0050 + (port) * 0x1000)
#define MV_GMAC_QSGMII_STATUS_QSGMII_STATUS_OFFS		0
#define MV_GMAC_QSGMII_STATUS_QSGMII_STATUS_MASK    \
		(0x000000ff << MV_GMAC_QSGMII_STATUS_QSGMII_STATUS_OFFS)


/* Qsgmii Prbs Counter */
#define MV_GMAC_QSGMII_PRBS_CNTR_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x0054 + (port) * 0x1000)
#define MV_GMAC_QSGMII_PRBS_CNTR_QSGMII_PRBS_ERR_CNT_REG_OFFS		0
#define MV_GMAC_QSGMII_PRBS_CNTR_QSGMII_PRBS_ERR_CNT_REG_MASK    \
		(0x0000ffff << MV_GMAC_QSGMII_PRBS_CNTR_QSGMII_PRBS_ERR_CNT_REG_OFFS)


/* Ccfc Port Speed Timer%p */
#define MV_GMAC_CCFC_PORT_SPEED_TIMER_REG(port, t)		(MV_GMAC_UNIT_OFFSET + 0x0058 + t*4 + (port) * 0x1000)
#define MV_GMAC_CCFC_PORT_SPEED_TIMER_PORTSPEEDTIMER_OFFS		0
#define MV_GMAC_CCFC_PORT_SPEED_TIMER_PORTSPEEDTIMER_MASK    \
		(0x0000ffff << MV_GMAC_CCFC_PORT_SPEED_TIMER_PORTSPEEDTIMER_OFFS)


/* Fc Dsa Tag %n */
#define MV_GMAC_FC_DSA_TAG_REG(port, n)			(MV_GMAC_UNIT_OFFSET + 0x0078 + 4*n + (port) * 0x1000)
#define MV_GMAC_FC_DSA_TAG_DSATAGREGN_OFFS		0
#define MV_GMAC_FC_DSA_TAG_DSATAGREGN_MASK    \
		(0x0000ffff << MV_GMAC_FC_DSA_TAG_DSATAGREGN_OFFS)


/* Link Level Flow Control Window Reg 0 */
#define MV_GMAC_LINK_LEVEL_FLOW_CTRL_WINDOW_REG_0(port)		(MV_GMAC_UNIT_OFFSET + 0x0088 + (port) * 0x1000)
#define MV_GMAC_LINK_LEVEL_FLOW_CTRL_WINDOW_REG_0_LLFC_FC_WINDOW_REG0_OFFS		0
#define MV_GMAC_LINK_LEVEL_FLOW_CTRL_WINDOW_REG_0_LLFC_FC_WINDOW_REG0_MASK    \
		(0x0000ffff << MV_GMAC_LINK_LEVEL_FLOW_CTRL_WINDOW_REG_0_LLFC_FC_WINDOW_REG0_OFFS)


/* Link Level Flow Control Window Reg 1 */
#define MV_GMAC_LINK_LEVEL_FLOW_CTRL_WINDOW_REG_1(port)		(MV_GMAC_UNIT_OFFSET + 0x008c + (port) * 0x1000)
#define MV_GMAC_LINK_LEVEL_FLOW_CTRL_WINDOW_REG_1_LLFC_FC_WINDOW_REG1_OFFS		0
#define MV_GMAC_LINK_LEVEL_FLOW_CTRL_WINDOW_REG_1_LLFC_FC_WINDOW_REG1_MASK    \
		(0x00007fff << MV_GMAC_LINK_LEVEL_FLOW_CTRL_WINDOW_REG_1_LLFC_FC_WINDOW_REG1_OFFS)

#define MV_GMAC_LINK_LEVEL_FLOW_CTRL_WINDOW_REG_1_LLFC_RATE_LIMIT_EN_OFFS		15
#define MV_GMAC_LINK_LEVEL_FLOW_CTRL_WINDOW_REG_1_LLFC_RATE_LIMIT_EN_MASK    \
		(0x00000001 << MV_GMAC_LINK_LEVEL_FLOW_CTRL_WINDOW_REG_1_LLFC_RATE_LIMIT_EN_OFFS)


/* Port Mac Control4 */
#define MV_GMAC_PORT_CTRL4_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x0090 + (port) * 0x1000)
#define MV_GMAC_PORT_CTRL4_EXT_PIN_GMII_SEL_OFFS		0
#define MV_GMAC_PORT_CTRL4_EXT_PIN_GMII_SEL_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL4_EXT_PIN_GMII_SEL_OFFS)

#define MV_GMAC_PORT_CTRL4_PREAMBLE_FIX_OFFS		1
#define MV_GMAC_PORT_CTRL4_PREAMBLE_FIX_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL4_PREAMBLE_FIX_OFFS)

#define MV_GMAC_PORT_CTRL4_SQ_DETECT_FIX_EN_OFFS		2
#define MV_GMAC_PORT_CTRL4_SQ_DETECT_FIX_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL4_SQ_DETECT_FIX_EN_OFFS)

#define MV_GMAC_PORT_CTRL4_FC_EN_RX_OFFS		3
#define MV_GMAC_PORT_CTRL4_FC_EN_RX_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL4_FC_EN_RX_OFFS)

#define MV_GMAC_PORT_CTRL4_FC_EN_TX_OFFS		4
#define MV_GMAC_PORT_CTRL4_FC_EN_TX_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL4_FC_EN_TX_OFFS)

#define MV_GMAC_PORT_CTRL4_DP_CLK_SEL_OFFS		5
#define MV_GMAC_PORT_CTRL4_DP_CLK_SEL_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL4_DP_CLK_SEL_OFFS)

#define MV_GMAC_PORT_CTRL4_SYNC_BYPASS_OFFS		6
#define MV_GMAC_PORT_CTRL4_SYNC_BYPASS_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL4_SYNC_BYPASS_OFFS)

#define MV_GMAC_PORT_CTRL4_QSGMII_BYPASS_ACTIVE_OFFS		7
#define MV_GMAC_PORT_CTRL4_QSGMII_BYPASS_ACTIVE_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL4_QSGMII_BYPASS_ACTIVE_OFFS)

#define MV_GMAC_PORT_CTRL4_COUNT_EXTERNAL_FC_EN_OFFS		8
#define MV_GMAC_PORT_CTRL4_COUNT_EXTERNAL_FC_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL4_COUNT_EXTERNAL_FC_EN_OFFS)

#define MV_GMAC_PORT_CTRL4_MARVELL_HEADER_EN_OFFS		9
#define MV_GMAC_PORT_CTRL4_MARVELL_HEADER_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_CTRL4_MARVELL_HEADER_EN_OFFS)

#define MV_GMAC_PORT_CTRL4_LEDS_NUMBER_OFFS		10
#define MV_GMAC_PORT_CTRL4_LEDS_NUMBER_MASK    \
		(0x0000003f << MV_GMAC_PORT_CTRL4_LEDS_NUMBER_OFFS)


/* Port Serial Parameters 1 Configuration */
#define MV_GMAC_PORT_SERIAL_PARAM_1_CFG_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x0094 + (port) * 0x1000)
#define MV_GMAC_PORT_SERIAL_PARAM_1_CFG_RX_STANDARD_PRBS7_OFFS		0
#define MV_GMAC_PORT_SERIAL_PARAM_1_CFG_RX_STANDARD_PRBS7_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_1_CFG_RX_STANDARD_PRBS7_OFFS)

#define MV_GMAC_PORT_SERIAL_PARAM_1_CFG_FORWARD_PFC_EN_OFFS		1
#define MV_GMAC_PORT_SERIAL_PARAM_1_CFG_FORWARD_PFC_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_1_CFG_FORWARD_PFC_EN_OFFS)

#define MV_GMAC_PORT_SERIAL_PARAM_1_CFG_FORWARD_UNKNOWN_FC_EN_OFFS		2
#define MV_GMAC_PORT_SERIAL_PARAM_1_CFG_FORWARD_UNKNOWN_FC_EN_MASK    \
		(0x00000001 << MV_GMAC_PORT_SERIAL_PARAM_1_CFG_FORWARD_UNKNOWN_FC_EN_OFFS)


/* Lpi Control 0 */
#define MV_GMAC_LPI_CTRL_0_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x00c0 + (port) * 0x1000)
#define MV_GMAC_LPI_CTRL_0_LI_LIMIT_OFFS		0
#define MV_GMAC_LPI_CTRL_0_LI_LIMIT_MASK    \
		(0x000000ff << MV_GMAC_LPI_CTRL_0_LI_LIMIT_OFFS)

#define MV_GMAC_LPI_CTRL_0_TS_LIMIT_OFFS		8
#define MV_GMAC_LPI_CTRL_0_TS_LIMIT_MASK    \
		(0x000000ff << MV_GMAC_LPI_CTRL_0_TS_LIMIT_OFFS)


/* Lpi Control 1 */
#define MV_GMAC_LPI_CTRL_1_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x00c4 + (port) * 0x1000)
#define MV_GMAC_LPI_CTRL_1_LPI_REQUEST_EN_OFFS		0
#define MV_GMAC_LPI_CTRL_1_LPI_REQUEST_EN_MASK    \
		(0x00000001 << MV_GMAC_LPI_CTRL_1_LPI_REQUEST_EN_OFFS)

#define MV_GMAC_LPI_CTRL_1_LPI_REQUEST_FORCE_OFFS		1
#define MV_GMAC_LPI_CTRL_1_LPI_REQUEST_FORCE_MASK    \
		(0x00000001 << MV_GMAC_LPI_CTRL_1_LPI_REQUEST_FORCE_OFFS)

#define MV_GMAC_LPI_CTRL_1_LPI_MANUAL_MODE_OFFS		2
#define MV_GMAC_LPI_CTRL_1_LPI_MANUAL_MODE_MASK    \
		(0x00000001 << MV_GMAC_LPI_CTRL_1_LPI_MANUAL_MODE_OFFS)

#define MV_GMAC_LPI_CTRL_1_EN_GTX_CLK_HALT_OFFS		3
#define MV_GMAC_LPI_CTRL_1_EN_GTX_CLK_HALT_MASK    \
		(0x00000001 << MV_GMAC_LPI_CTRL_1_EN_GTX_CLK_HALT_OFFS)

#define MV_GMAC_LPI_CTRL_1_TW_LIMIT_OFFS		4
#define MV_GMAC_LPI_CTRL_1_TW_LIMIT_MASK    \
		(0x00000fff << MV_GMAC_LPI_CTRL_1_TW_LIMIT_OFFS)


/* Lpi Control 2 */
#define MV_GMAC_LPI_CTRL_2_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x00c8 + (port) * 0x1000)
#define MV_GMAC_LPI_CTRL_2_LPI_CLK_DIV_OFFS		0
#define MV_GMAC_LPI_CTRL_2_LPI_CLK_DIV_MASK    \
		(0x0000007f << MV_GMAC_LPI_CTRL_2_LPI_CLK_DIV_OFFS)

#define MV_GMAC_LPI_CTRL_2_PCS_RX_ER_MASK_DISABLE_OFFS		7
#define MV_GMAC_LPI_CTRL_2_PCS_RX_ER_MASK_DISABLE_MASK    \
		(0x00000001 << MV_GMAC_LPI_CTRL_2_PCS_RX_ER_MASK_DISABLE_OFFS)

#define MV_GMAC_LPI_CTRL_2_EN_GMII2MII_LPI_FIX_OFFS		8
#define MV_GMAC_LPI_CTRL_2_EN_GMII2MII_LPI_FIX_MASK    \
		(0x00000001 << MV_GMAC_LPI_CTRL_2_EN_GMII2MII_LPI_FIX_OFFS)


/* Lpi Status */
#define MV_GMAC_LPI_STATUS_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x00cc + (port) * 0x1000)
#define MV_GMAC_LPI_STATUS_PCS_RX_LPI_STATUS_OFFS		0
#define MV_GMAC_LPI_STATUS_PCS_RX_LPI_STATUS_MASK    \
		(0x00000001 << MV_GMAC_LPI_STATUS_PCS_RX_LPI_STATUS_OFFS)

#define MV_GMAC_LPI_STATUS_PCS_TX_LPI_STATUS_OFFS		1
#define MV_GMAC_LPI_STATUS_PCS_TX_LPI_STATUS_MASK    \
		(0x00000001 << MV_GMAC_LPI_STATUS_PCS_TX_LPI_STATUS_OFFS)

#define MV_GMAC_LPI_STATUS_MAC_RX_LP_IDLE_STATUS_OFFS		2
#define MV_GMAC_LPI_STATUS_MAC_RX_LP_IDLE_STATUS_MASK    \
		(0x00000001 << MV_GMAC_LPI_STATUS_MAC_RX_LP_IDLE_STATUS_OFFS)

#define MV_GMAC_LPI_STATUS_MAC_TX_LP_WAIT_STATUS_OFFS		3
#define MV_GMAC_LPI_STATUS_MAC_TX_LP_WAIT_STATUS_MASK    \
		(0x00000001 << MV_GMAC_LPI_STATUS_MAC_TX_LP_WAIT_STATUS_OFFS)

#define MV_GMAC_LPI_STATUS_MAC_TX_LP_IDLE_STATUS_OFFS		4
#define MV_GMAC_LPI_STATUS_MAC_TX_LP_IDLE_STATUS_MASK    \
		(0x00000001 << MV_GMAC_LPI_STATUS_MAC_TX_LP_IDLE_STATUS_OFFS)


/* Lpi Counter */
#define MV_GMAC_LPI_CNTR_REG(port)				(MV_GMAC_UNIT_OFFSET + 0x00d0 + (port) * 0x1000)
#define MV_GMAC_LPI_CNTR_LPI_COUNTER_OFFS		0
#define MV_GMAC_LPI_CNTR_LPI_COUNTER_MASK    \
		(0x0000ffff << MV_GMAC_LPI_CNTR_LPI_COUNTER_OFFS)


/* Pulse 1 Ms Low */
#define MV_GMAC_PULSE_1_MS_LOW_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x00d4 + (port) * 0x1000)
#define MV_GMAC_PULSE_1_MS_LOW_PULSE_1MS_MAX_LOW_OFFS		0
#define MV_GMAC_PULSE_1_MS_LOW_PULSE_1MS_MAX_LOW_MASK    \
		(0x0000ffff << MV_GMAC_PULSE_1_MS_LOW_PULSE_1MS_MAX_LOW_OFFS)


/* Pulse 1 Ms High */
#define MV_GMAC_PULSE_1_MS_HIGH_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x00d8 + (port) * 0x1000)
#define MV_GMAC_PULSE_1_MS_HIGH_PULSE_1MS_MAX_HIGH_OFFS		0
#define MV_GMAC_PULSE_1_MS_HIGH_PULSE_1MS_MAX_HIGH_MASK    \
		(0x0000ffff << MV_GMAC_PULSE_1_MS_HIGH_PULSE_1MS_MAX_HIGH_OFFS)

/* Port Interrupt Cause */
#define MV_GMAC_INTERRUPT_CAUSE_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x0020 + (port) * 0x1000)
/* Port Interrupt Mask */
#define MV_GMAC_INTERRUPT_MASK_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x0024 + (port) * 0x1000)
#define MV_GMAC_INTERRUPT_CAUSE_LINK_CHANGE_OFFS		1
#define MV_GMAC_INTERRUPT_CAUSE_LINK_CHANGE_MASK		(0x1 << MV_GMAC_INTERRUPT_CAUSE_LINK_CHANGE_OFFS)

/* Port Interrupt Summary Cause */
#define MV_GMAC_INTERRUPT_SUM_CAUSE_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x00A0 + (port) * 0x1000)
/* Port Interrupt Summary Mask */
#define MV_GMAC_INTERRUPT_SUM_MASK_REG(port)			(MV_GMAC_UNIT_OFFSET + 0x00A4 + (port) * 0x1000)
#define MV_GMAC_INTERRUPT_SUM_CAUSE_LINK_CHANGE_OFFS		1
#define MV_GMAC_INTERRUPT_SUM_CAUSE_LINK_CHANGE_MASK		(0x1 << MV_GMAC_INTERRUPT_SUM_CAUSE_LINK_CHANGE_OFFS)

#endif /* __mv_gmac_regs_h__ */
