/*******************************************************************************
Copyright (C) Marvell International Ltd. and its affiliates

This software file (the "File") is owned and distributed by Marvell
International Ltd. and/or its affiliates ("Marvell") under the following
alternative licensing terms.  Once you have made an election to distribute the
File under one of the following license alternatives, please (i) delete this
introductory statement regarding license alternatives, (ii) delete the two
license alternatives that you have not elected to use and (iii) preserve the
Marvell copyright notice above.


********************************************************************************
Marvell GPL License Option

If you received this File from Marvell, you may opt to use, redistribute and/or
modify this File in accordance with the terms and conditions of the General
Public License Version 2, June 1991 (the "GPL License"), a copy of which is
available along with the File in the license.txt file or by writing to the Free
Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 or
on the worldwide web at http://www.gnu.org/licenses/gpl.txt.

THE FILE IS DISTRIBUTED AS-IS, WITHOUT WARRANTY OF ANY KIND, AND THE IMPLIED
WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY
DISCLAIMED.  The GPL License provides additional details about this warranty
disclaimer.
*******************************************************************************/
#ifndef __mv_xlg_mac_regs_h__
#define __mv_xlg_mac_regs_h__

/* includes */

/* unit offset */
#define MV_PP3_XLG_MAC_UNIT_OFFSET		0x030C0000


/* Port Mac Control0 */
#define MV_XLG_PORT_MAC_CTRL0_REG(port)			(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0000 + (port) * 0x1000))
#define MV_XLG_MAC_CTRL0_PORTEN_OFFS		0
#define MV_XLG_MAC_CTRL0_PORTEN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL0_PORTEN_OFFS)

#define MV_XLG_MAC_CTRL0_MACRESETN_OFFS		1
#define MV_XLG_MAC_CTRL0_MACRESETN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL0_MACRESETN_OFFS)

#define MV_XLG_MAC_CTRL0_FORCELINKDOWN_OFFS		2
#define MV_XLG_MAC_CTRL0_FORCELINKDOWN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL0_FORCELINKDOWN_OFFS)

#define MV_XLG_MAC_CTRL0_FORCELINKPASS_OFFS		3
#define MV_XLG_MAC_CTRL0_FORCELINKPASS_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL0_FORCELINKPASS_OFFS)

#define MV_XLG_MAC_CTRL0_TXIPGMODE_OFFS		5
#define MV_XLG_MAC_CTRL0_TXIPGMODE_MASK    \
		(0x00000003 << MV_XLG_MAC_CTRL0_TXIPGMODE_OFFS)

#define MV_XLG_MAC_CTRL0_RXFCEN_OFFS		7
#define MV_XLG_MAC_CTRL0_RXFCEN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL0_RXFCEN_OFFS)

#define MV_XLG_MAC_CTRL0_TXFCEN_OFFS		8
#define MV_XLG_MAC_CTRL0_TXFCEN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL0_TXFCEN_OFFS)

#define MV_XLG_MAC_CTRL0_RXCRCCHECKEN_OFFS		9
#define MV_XLG_MAC_CTRL0_RXCRCCHECKEN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL0_RXCRCCHECKEN_OFFS)

#define MV_XLG_MAC_CTRL0_PERIODICXONEN_OFFS		10
#define MV_XLG_MAC_CTRL0_PERIODICXONEN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL0_PERIODICXONEN_OFFS)

#define MV_XLG_MAC_CTRL0_RXCRCSTRIPEN_OFFS		11
#define MV_XLG_MAC_CTRL0_RXCRCSTRIPEN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL0_RXCRCSTRIPEN_OFFS)

#define MV_XLG_MAC_CTRL0_PADDINGDIS_OFFS		13
#define MV_XLG_MAC_CTRL0_PADDINGDIS_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL0_PADDINGDIS_OFFS)

#define MV_XLG_MAC_CTRL0_MIBCNTDIS_OFFS		14
#define MV_XLG_MAC_CTRL0_MIBCNTDIS_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL0_MIBCNTDIS_OFFS)

#define MV_XLG_MAC_CTRL0_PFC_CASCADE_PORT_ENABLE_OFFS		15
#define MV_XLG_MAC_CTRL0_PFC_CASCADE_PORT_ENABLE_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL0_PFC_CASCADE_PORT_ENABLE_OFFS)


/* Port Mac Control1 */
#define MV_XLG_PORT_MAC_CTRL1_REG(port)			(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0004 + (port) * 0x1000))
#define MV_XLG_MAC_CTRL1_FRAMESIZELIMIT_OFFS		0
#define MV_XLG_MAC_CTRL1_FRAMESIZELIMIT_MASK    \
		(0x00001fff << MV_XLG_MAC_CTRL1_FRAMESIZELIMIT_OFFS)

#define MV_XLG_MAC_CTRL1_MACLOOPBACKEN_OFFS		13
#define MV_XLG_MAC_CTRL1_MACLOOPBACKEN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL1_MACLOOPBACKEN_OFFS)

#define MV_XLG_MAC_CTRL1_XGMIILOOPBACKEN_OFFS		14
#define MV_XLG_MAC_CTRL1_XGMIILOOPBACKEN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL1_XGMIILOOPBACKEN_OFFS)

#define MV_XLG_MAC_CTRL1_LOOPBACKCLOCKSELECT_OFFS		15
#define MV_XLG_MAC_CTRL1_LOOPBACKCLOCKSELECT_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL1_LOOPBACKCLOCKSELECT_OFFS)


/* Port Mac Control2 */
#define MV_XLG_PORT_MAC_CTRL2_REG(port)			(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0008 + (port) * 0x1000))
#define MV_XLG_MAC_CTRL2_SALOW_7_0_OFFS		0
#define MV_XLG_MAC_CTRL2_SALOW_7_0_MASK    \
		(0x000000ff << MV_XLG_MAC_CTRL2_SALOW_7_0_OFFS)

#define MV_XLG_MAC_CTRL2_UNIDIRECTIONALEN_OFFS		8
#define MV_XLG_MAC_CTRL2_UNIDIRECTIONALEN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL2_UNIDIRECTIONALEN_OFFS)

#define MV_XLG_MAC_CTRL2_FIXEDIPGBASE_OFFS		9
#define MV_XLG_MAC_CTRL2_FIXEDIPGBASE_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL2_FIXEDIPGBASE_OFFS)

#define MV_XLG_MAC_CTRL2_PERIODICXOFFEN_OFFS		10
#define MV_XLG_MAC_CTRL2_PERIODICXOFFEN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL2_PERIODICXOFFEN_OFFS)

#define MV_XLG_MAC_CTRL2_SIMPLEXMODEEN_OFFS		13
#define MV_XLG_MAC_CTRL2_SIMPLEXMODEEN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL2_SIMPLEXMODEEN_OFFS)

#define MV_XLG_MAC_CTRL2_FC_MODE_OFFS		14
#define MV_XLG_MAC_CTRL2_FC_MODE_MASK    \
		(0x00000003 << MV_XLG_MAC_CTRL2_FC_MODE_OFFS)


/* Port Status */
#define MV_XLG_MAC_PORT_STATUS_REG(port)		(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x000c + (port) * 0x1000))
#define MV_XLG_MAC_PORT_STATUS_LINKSTATUS_OFFS		0
#define MV_XLG_MAC_PORT_STATUS_LINKSTATUS_MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_STATUS_LINKSTATUS_OFFS)

#define MV_XLG_MAC_PORT_STATUS_REMOTEFAULT_OFFS		1
#define MV_XLG_MAC_PORT_STATUS_REMOTEFAULT_MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_STATUS_REMOTEFAULT_OFFS)

#define MV_XLG_MAC_PORT_STATUS_LOCALFAULT_OFFS		2
#define MV_XLG_MAC_PORT_STATUS_LOCALFAULT_MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_STATUS_LOCALFAULT_OFFS)

#define MV_XLG_MAC_PORT_STATUS_LINKSTATUSCLEAN_OFFS		3
#define MV_XLG_MAC_PORT_STATUS_LINKSTATUSCLEAN_MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_STATUS_LINKSTATUSCLEAN_OFFS)

#define MV_XLG_MAC_PORT_STATUS_LOCALFAULTCLEAN_OFFS		4
#define MV_XLG_MAC_PORT_STATUS_LOCALFAULTCLEAN_MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_STATUS_LOCALFAULTCLEAN_OFFS)

#define MV_XLG_MAC_PORT_STATUS_REMOTEFAULTCLEAN_OFFS		5
#define MV_XLG_MAC_PORT_STATUS_REMOTEFAULTCLEAN_MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_STATUS_REMOTEFAULTCLEAN_OFFS)

#define MV_XLG_MAC_PORT_STATUS_PORTRXPAUSE_OFFS		6
#define MV_XLG_MAC_PORT_STATUS_PORTRXPAUSE_MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_STATUS_PORTRXPAUSE_OFFS)

#define MV_XLG_MAC_PORT_STATUS_PORTTXPAUSE_OFFS		7
#define MV_XLG_MAC_PORT_STATUS_PORTTXPAUSE_MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_STATUS_PORTTXPAUSE_OFFS)

#define MV_XLG_MAC_PORT_STATUS_PFC_SYNC_FIFO_FULL_OFFS		8
#define MV_XLG_MAC_PORT_STATUS_PFC_SYNC_FIFO_FULL_MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_STATUS_PFC_SYNC_FIFO_FULL_OFFS)


/* Port Fifos Thresholds Configuration */
#define MV_XLG_PORT_FIFOS_THRS_CFG_REG(port)		(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0010 + (port) * 0x1000))
#define MV_XLG_MAC_PORT_FIFOS_THRS_CFG_RXFULLTHR_OFFS		0
#define MV_XLG_MAC_PORT_FIFOS_THRS_CFG_RXFULLTHR_MASK    \
		(0x0000001f << MV_XLG_MAC_PORT_FIFOS_THRS_CFG_RXFULLTHR_OFFS)

#define MV_XLG_MAC_PORT_FIFOS_THRS_CFG_TXFIFOSIZE_OFFS		5
#define MV_XLG_MAC_PORT_FIFOS_THRS_CFG_TXFIFOSIZE_MASK    \
		(0x0000003f << MV_XLG_MAC_PORT_FIFOS_THRS_CFG_TXFIFOSIZE_OFFS)

#define MV_XLG_MAC_PORT_FIFOS_THRS_CFG_TXRDTHR_OFFS		11
#define MV_XLG_MAC_PORT_FIFOS_THRS_CFG_TXRDTHR_MASK    \
		(0x0000001f << MV_XLG_MAC_PORT_FIFOS_THRS_CFG_TXRDTHR_OFFS)


/* Port Mac Control3 */
#define MV_XLG_PORT_MAC_CTRL3_REG(port)			(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x001c + (port) * 0x1000))
#define MV_XLG_MAC_CTRL3_BUFSIZE_OFFS		0
#define MV_XLG_MAC_CTRL3_BUFSIZE_MASK    \
		(0x0000003f << MV_XLG_MAC_CTRL3_BUFSIZE_OFFS)

#define MV_XLG_MAC_CTRL3_XTRAIPG_OFFS		6
#define MV_XLG_MAC_CTRL3_XTRAIPG_MASK    \
		(0x0000007f << MV_XLG_MAC_CTRL3_XTRAIPG_OFFS)

#define MV_XLG_MAC_CTRL3_MACMODESELECT_OFFS		13
#define MV_XLG_MAC_CTRL3_MACMODESELECT_MASK    \
		(0x00000007 << MV_XLG_MAC_CTRL3_MACMODESELECT_OFFS)


/* Port Per Prio Flow Control Status */
#define MV_XLG_PORT_PER_PRIO_FLOW_CTRL_STATUS_REG(port)      (MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0020 + (port) * 0x1000))
#define MV_XLG_MAC_PORT_PER_PRIO_FLOW_CTRL_STATUS_PRIONSTATUS_OFFS		0
#define MV_XLG_MAC_PORT_PER_PRIO_FLOW_CTRL_STATUS_PRIONSTATUS_MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_PER_PRIO_FLOW_CTRL_STATUS_PRIONSTATUS_OFFS)


/* Debug Bus Status */
#define MV_XLG_DEBUG_BUS_STATUS_REG(port)		(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0024 + (port) * 0x1000))
#define MV_XLG_MAC_DEBUG_BUS_STATUS_DEBUG_BUS_OFFS		0
#define MV_XLG_MAC_DEBUG_BUS_STATUS_DEBUG_BUS_MASK    \
		(0x0000ffff << MV_XLG_MAC_DEBUG_BUS_STATUS_DEBUG_BUS_OFFS)


/* Port Metal Fix */
#define MV_XLG_PORT_METAL_FIX_REG(port)			(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x002c + (port) * 0x1000))
#define MV_XLG_MAC_PORT_METAL_FIX_EN_EOP_IN_FIFO__OFFS		0
#define MV_XLG_MAC_PORT_METAL_FIX_EN_EOP_IN_FIFO__MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_METAL_FIX_EN_EOP_IN_FIFO__OFFS)

#define MV_XLG_MAC_PORT_METAL_FIX_EN_LTF_FIX__OFFS		1
#define MV_XLG_MAC_PORT_METAL_FIX_EN_LTF_FIX__MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_METAL_FIX_EN_LTF_FIX__OFFS)

#define MV_XLG_MAC_PORT_METAL_FIX_EN_HOLD_FIX__OFFS		2
#define MV_XLG_MAC_PORT_METAL_FIX_EN_HOLD_FIX__MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_METAL_FIX_EN_HOLD_FIX__OFFS)

#define MV_XLG_MAC_PORT_METAL_FIX_EN_LED_FIX__OFFS		3
#define MV_XLG_MAC_PORT_METAL_FIX_EN_LED_FIX__MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_METAL_FIX_EN_LED_FIX__OFFS)

#define MV_XLG_MAC_PORT_METAL_FIX_EN_PAD_PROTECT__OFFS		4
#define MV_XLG_MAC_PORT_METAL_FIX_EN_PAD_PROTECT__MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_METAL_FIX_EN_PAD_PROTECT__OFFS)

#define MV_XLG_MAC_PORT_METAL_FIX_EN_NX_BTS44__OFFS		5
#define MV_XLG_MAC_PORT_METAL_FIX_EN_NX_BTS44__MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_METAL_FIX_EN_NX_BTS44__OFFS)

#define MV_XLG_MAC_PORT_METAL_FIX_EN_NX_BTS42__OFFS		6
#define MV_XLG_MAC_PORT_METAL_FIX_EN_NX_BTS42__MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_METAL_FIX_EN_NX_BTS42__OFFS)

#define MV_XLG_MAC_PORT_METAL_FIX_EN_FLUSH_FIX_OFFS		7
#define MV_XLG_MAC_PORT_METAL_FIX_EN_FLUSH_FIX_MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_METAL_FIX_EN_FLUSH_FIX_OFFS)

#define MV_XLG_MAC_PORT_METAL_FIX_EN_PORT_EN_FIX_OFFS		8
#define MV_XLG_MAC_PORT_METAL_FIX_EN_PORT_EN_FIX_MASK    \
		(0x00000001 << MV_XLG_MAC_PORT_METAL_FIX_EN_PORT_EN_FIX_OFFS)

#define MV_XLG_MAC_PORT_METAL_FIX_SPARE_DEF0_BITS_OFFS		9
#define MV_XLG_MAC_PORT_METAL_FIX_SPARE_DEF0_BITS_MASK    \
		(0x0000000f << MV_XLG_MAC_PORT_METAL_FIX_SPARE_DEF0_BITS_OFFS)

#define MV_XLG_MAC_PORT_METAL_FIX_SPARE_DEF1_BITS_OFFS		13
#define MV_XLG_MAC_PORT_METAL_FIX_SPARE_DEF1_BITS_MASK    \
		(0x00000007 << MV_XLG_MAC_PORT_METAL_FIX_SPARE_DEF1_BITS_OFFS)


/* Xg Mib Counters Control */
#define MV_XLG_MIB_CNTRS_CTRL_REG(port)			(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0030 + (port) * 0x1000))
#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_XGCAPTURETRIGGER_OFFS		0
#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_XGCAPTURETRIGGER_MASK    \
		(0x00000001 << MV_XLG_MAC_XG_MIB_CNTRS_CTRL_XGCAPTURETRIGGER_OFFS)

#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_XGDONTCLEARAFTERREAD_OFFS		1
#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_XGDONTCLEARAFTERREAD_MASK    \
		(0x00000001 << MV_XLG_MAC_XG_MIB_CNTRS_CTRL_XGDONTCLEARAFTERREAD_OFFS)

#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_XGRXHISTOGRAMEN_OFFS		2
#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_XGRXHISTOGRAMEN_MASK    \
		(0x00000001 << MV_XLG_MAC_XG_MIB_CNTRS_CTRL_XGRXHISTOGRAMEN_OFFS)

#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_XGTXHISTOGRAMEN_OFFS		3
#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_XGTXHISTOGRAMEN_MASK    \
		(0x00000001 << MV_XLG_MAC_XG_MIB_CNTRS_CTRL_XGTXHISTOGRAMEN_OFFS)

#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_MFA1_BTT940_FIX_ENABLE__OFFS		4
#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_MFA1_BTT940_FIX_ENABLE__MASK    \
		(0x00000001 << MV_XLG_MAC_XG_MIB_CNTRS_CTRL_MFA1_BTT940_FIX_ENABLE__OFFS)

#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_LEDS_NUMBER_OFFS		5
#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_LEDS_NUMBER_MASK    \
		(0x0000003f << MV_XLG_MAC_XG_MIB_CNTRS_CTRL_LEDS_NUMBER_OFFS)

#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_MIB_4_COUNT_HIST_OFFS		11
#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_MIB_4_COUNT_HIST_MASK    \
		(0x00000001 << MV_XLG_MAC_XG_MIB_CNTRS_CTRL_MIB_4_COUNT_HIST_OFFS)

#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_MIB_4_LIMIT_1518_1522_OFFS		12
#define MV_XLG_MAC_XG_MIB_CNTRS_CTRL_MIB_4_LIMIT_1518_1522_MASK    \
		(0x00000001 << MV_XLG_MAC_XG_MIB_CNTRS_CTRL_MIB_4_LIMIT_1518_1522_OFFS)


/* Cn/ccfc Timer%i */
#define MV_XLG_CNCCFC_TIMERI_REG(port, t)		(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0038 + (port) * 0x1000 + t*4))
#define MV_XLG_MAC_CNCCFC_TIMERI_PORTSPEEDTIMER_OFFS	0
#define MV_XLG_MAC_CNCCFC_TIMERI_PORTSPEEDTIMER_MASK    \
		(0x0000ffff << MV_XLG_MAC_CNCCFC_TIMERI_PORTSPEEDTIMER_OFFS)


/* Ppfc Control */
#define MV_XLG_MAC_PPFC_CTRL_REG(port)			(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0060 + (port) * 0x1000))
#define MV_XLG_MAC_PPFC_CTRL_GLOBAL_PAUSE_ENI_OFFS		0
#define MV_XLG_MAC_PPFC_CTRL_GLOBAL_PAUSE_ENI_MASK    \
		(0x00000001 << MV_XLG_MAC_PPFC_CTRL_GLOBAL_PAUSE_ENI_OFFS)

#define MV_XLG_MAC_PPFC_CTRL_DIP_BTS_677_EN_OFFS		9
#define MV_XLG_MAC_PPFC_CTRL_DIP_BTS_677_EN_MASK    \
		(0x00000001 << MV_XLG_MAC_PPFC_CTRL_DIP_BTS_677_EN_OFFS)


/* Fc Dsa Tag 0 */
#define MV_XLG_MAC_FC_DSA_TAG_0_REG(port)		(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0068 + (port) * 0x1000))
#define MV_XLG_MAC_FC_DSA_TAG_0_DSATAGREG0_OFFS		0
#define MV_XLG_MAC_FC_DSA_TAG_0_DSATAGREG0_MASK    \
		(0x0000ffff << MV_XLG_MAC_FC_DSA_TAG_0_DSATAGREG0_OFFS)


/* Fc Dsa Tag 1 */
#define MV_XLG_MAC_FC_DSA_TAG_1_REG(port)		(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x006c + (port) * 0x1000))
#define MV_XLG_MAC_FC_DSA_TAG_1_DSATAGREG1_OFFS		0
#define MV_XLG_MAC_FC_DSA_TAG_1_DSATAGREG1_MASK    \
		(0x0000ffff << MV_XLG_MAC_FC_DSA_TAG_1_DSATAGREG1_OFFS)


/* Fc Dsa Tag 2 */
#define MV_XLG_MAC_FC_DSA_TAG_2_REG(port)		(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0070 + (port) * 0x1000))
#define MV_XLG_MAC_FC_DSA_TAG_2_DSATAGREG2_OFFS		0
#define MV_XLG_MAC_FC_DSA_TAG_2_DSATAGREG2_MASK    \
		(0x0000ffff << MV_XLG_MAC_FC_DSA_TAG_2_DSATAGREG2_OFFS)


/* Fc Dsa Tag 3 */
#define MV_XLG_MAC_FC_DSA_TAG_3_REG(port)		(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0074 + (port) * 0x1000))
#define MV_XLG_MAC_FC_DSA_TAG_3_DSATAGREG3_OFFS		0
#define MV_XLG_MAC_FC_DSA_TAG_3_DSATAGREG3_MASK    \
		(0x0000ffff << MV_XLG_MAC_FC_DSA_TAG_3_DSATAGREG3_OFFS)


/* Dic Budget Compensation */
#define MV_XLG_MAC_DIC_BUDGET_COMPENSATION_REG(port)	(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0080 + (port) * 0x1000))
#define MV_XLG_MAC_DIC_BUDGET_COMPENSATION_DIC_COUNTER_TO_ADD_8BYTES_OFFS		0
#define MV_XLG_MAC_DIC_BUDGET_COMPENSATION_DIC_COUNTER_TO_ADD_8BYTES_MASK    \
		(0x0000ffff << MV_XLG_MAC_DIC_BUDGET_COMPENSATION_DIC_COUNTER_TO_ADD_8BYTES_OFFS)


/* Port Mac Control4 */
#define MV_XLG_PORT_MAC_CTRL4_REG(port)			(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0084 + (port) * 0x1000))
#define MV_XLG_MAC_CTRL4_LLFC_GLOBAL_FC_ENABLE_OFFS		0
#define MV_XLG_MAC_CTRL4_LLFC_GLOBAL_FC_ENABLE_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL4_LLFC_GLOBAL_FC_ENABLE_OFFS)

#define MV_XLG_MAC_CTRL4_LED_STREAM_SELECT_OFFS		1
#define MV_XLG_MAC_CTRL4_LED_STREAM_SELECT_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL4_LED_STREAM_SELECT_OFFS)

#define MV_XLG_MAC_CTRL4_DEBUG_BUS_SELECT_OFFS		2
#define MV_XLG_MAC_CTRL4_DEBUG_BUS_SELECT_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL4_DEBUG_BUS_SELECT_OFFS)

#define MV_XLG_MAC_CTRL4_MASK_PCS_RESET_OFFS		3
#define MV_XLG_MAC_CTRL4_MASK_PCS_RESET_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL4_MASK_PCS_RESET_OFFS)

#define MV_XLG_MAC_CTRL4_ENABLE_SHORT_PREAMBLE_FOR_XLG_OFFS		4
#define MV_XLG_MAC_CTRL4_ENABLE_SHORT_PREAMBLE_FOR_XLG_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL4_ENABLE_SHORT_PREAMBLE_FOR_XLG_OFFS)

#define MV_XLG_MAC_CTRL4_FORWARD_802_3X_FC_EN_OFFS		5
#define MV_XLG_MAC_CTRL4_FORWARD_802_3X_FC_EN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL4_FORWARD_802_3X_FC_EN_OFFS)

#define MV_XLG_MAC_CTRL4_FORWARD_PFC_EN_OFFS		6
#define MV_XLG_MAC_CTRL4_FORWARD_PFC_EN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL4_FORWARD_PFC_EN_OFFS)

#define MV_XLG_MAC_CTRL4_FORWARD_UNKNOWN_FC_EN_OFFS		7
#define MV_XLG_MAC_CTRL4_FORWARD_UNKNOWN_FC_EN_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL4_FORWARD_UNKNOWN_FC_EN_OFFS)

#define MV_XLG_MAC_CTRL4_USE_XPCS_OFFS		8
#define MV_XLG_MAC_CTRL4_USE_XPCS_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL4_USE_XPCS_OFFS)

#define MV_XLG_MAC_CTRL4_DMA_INTERFACE_IS_64_BIT_OFFS		9
#define MV_XLG_MAC_CTRL4_DMA_INTERFACE_IS_64_BIT_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL4_DMA_INTERFACE_IS_64_BIT_OFFS)

#define MV_XLG_MAC_CTRL4_TX_DMA_INTERFACE_BITS_OFFS		10
#define MV_XLG_MAC_CTRL4_TX_DMA_INTERFACE_BITS_MASK    \
		(0x00000003 << MV_XLG_MAC_CTRL4_TX_DMA_INTERFACE_BITS_OFFS)

#define MV_XLG_MAC_CTRL4_MAC_MODE_DMA_1G_OFFS		12
#define MV_XLG_MAC_CTRL4_MAC_MODE_DMA_1G_MASK    \
		(0x00000001 << MV_XLG_MAC_CTRL4_MAC_MODE_DMA_1G_OFFS)


/* Port Mac Control5 */
#define MV_XLG_PORT_MAC_CTRL5_REG(port)			(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0088 + (port) * 0x1000))
#define MV_XLG_MAC_CTRL5_TXIPGLENGTH_OFFS		0
#define MV_XLG_MAC_CTRL5_TXIPGLENGTH_MASK    \
		(0x0000000f << MV_XLG_MAC_CTRL5_TXIPGLENGTH_OFFS)

#define MV_XLG_MAC_CTRL5_PREAMBLELENGTHTX_OFFS		4
#define MV_XLG_MAC_CTRL5_PREAMBLELENGTHTX_MASK    \
		(0x00000007 << MV_XLG_MAC_CTRL5_PREAMBLELENGTHTX_OFFS)

#define MV_XLG_MAC_CTRL5_PREAMBLELENGTHRX_OFFS		7
#define MV_XLG_MAC_CTRL5_PREAMBLELENGTHRX_MASK    \
		(0x00000007 << MV_XLG_MAC_CTRL5_PREAMBLELENGTHRX_OFFS)

#define MV_XLG_MAC_CTRL5_TXNUMCRCBYTES_OFFS		10
#define MV_XLG_MAC_CTRL5_TXNUMCRCBYTES_MASK    \
		(0x00000007 << MV_XLG_MAC_CTRL5_TXNUMCRCBYTES_OFFS)

#define MV_XLG_MAC_CTRL5_RXNUMCRCBYTES_OFFS		13
#define MV_XLG_MAC_CTRL5_RXNUMCRCBYTES_MASK    \
		(0x00000007 << MV_XLG_MAC_CTRL5_RXNUMCRCBYTES_OFFS)


/* External Control */
#define MV_XLG_MAC_EXT_CTRL_REG(port)			(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0090 + (port) * 0x1000))
#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL0_OFFS		0
#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL0_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL0_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL1_OFFS		1
#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL1_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL1_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL2_OFFS		2
#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL2_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL2_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL3_OFFS		3
#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL3_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL3_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL4_OFFS		4
#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL4_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL4_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL5_OFFS		5
#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL5_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL5_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL6_OFFS		6
#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL6_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL6_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL7_OFFS		7
#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL7_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL7_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL8_OFFS		8
#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL8_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL8_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL9_OFFS		9
#define MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL9_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXTERNAL_CTRL9_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXT_CTRL_10_OFFS		10
#define MV_XLG_MAC_EXT_CTRL_EXT_CTRL_10_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXT_CTRL_10_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXT_CTRL_11_OFFS		11
#define MV_XLG_MAC_EXT_CTRL_EXT_CTRL_11_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXT_CTRL_11_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXT_CTRL_12_OFFS		12
#define MV_XLG_MAC_EXT_CTRL_EXT_CTRL_12_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXT_CTRL_12_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXT_CTRL_13_OFFS		13
#define MV_XLG_MAC_EXT_CTRL_EXT_CTRL_13_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXT_CTRL_13_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXT_CTRL_14_OFFS		14
#define MV_XLG_MAC_EXT_CTRL_EXT_CTRL_14_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXT_CTRL_14_OFFS)

#define MV_XLG_MAC_EXT_CTRL_EXT_CTRL_15_OFFS		15
#define MV_XLG_MAC_EXT_CTRL_EXT_CTRL_15_MASK    \
		(0x00000001 << MV_XLG_MAC_EXT_CTRL_EXT_CTRL_15_OFFS)


/* Macro Control */
#define MV_XLG_MAC_MACRO_CTRL_REG(port)			(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0094 + (port) * 0x1000))
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_0_OFFS		0
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_0_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_0_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_1_OFFS		1
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_1_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_1_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_2_OFFS		2
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_2_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_2_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_3_OFFS		3
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_3_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_3_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_4_OFFS		4
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_4_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_4_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_5_OFFS		5
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_5_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_5_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_6_OFFS		6
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_6_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_6_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_7_OFFS		7
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_7_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_7_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_8_OFFS		8
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_8_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_8_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_9_OFFS		9
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_9_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_9_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_10_OFFS		10
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_10_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_10_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_11_OFFS		11
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_11_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_11_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_12_OFFS		12
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_12_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_12_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_13_OFFS		13
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_13_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_13_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_14_OFFS		14
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_14_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_14_OFFS)

#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_15_OFFS		15
#define MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_15_MASK    \
		(0x00000001 << MV_XLG_MAC_MACRO_CTRL_MACRO_CTRL_15_OFFS)

#define MV_XLG_MAC_DIC_PPM_IPG_REDUCE_REG(port)		(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0094 + (port) * 0x1000))

/* Port Interrupt Cause */
#define MV_XLG_INTERRUPT_CAUSE_REG(port)		(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0014 + (port) * 0x1000))
/* Port Interrupt Mask */
#define MV_XLG_INTERRUPT_MASK_REG(port)			(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0018 + (port) * 0x1000))
#define MV_XLG_INTERRUPT_LINK_CHANGE_OFFS		1
#define MV_XLG_INTERRUPT_LINK_CHANGE_MASK		(0x1 << MV_XLG_INTERRUPT_LINK_CHANGE_OFFS)

/* Port Interrupt Summary Cause */
#define MV_XLG_EXTERNAL_INTERRUPT_CAUSE_REG(port)	(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x0058 + (port) * 0x1000))
/* Port Interrupt Summary Mask */
#define MV_XLG_EXTERNAL_INTERRUPT_MASK_REG(port)	(MV_PP3_XLG_MAC_UNIT_OFFSET + (0x005C + (port) * 0x1000))
#define MV_XLG_EXTERNAL_INTERRUPT_LINK_CHANGE_OFFS	1
#define MV_XLG_EXTERNAL_INTERRUPT_LINK_CHANGE_MASK	(0x1 << MV_XLG_EXTERNAL_INTERRUPT_LINK_CHANGE_OFFS)


#endif /* __mv_xlg_mac_regs_h__ */
