# SPDX-License-Identifier: GPL-2.0

obj-y					+= mub.o
obj-$(CONFIG_MARVELL_UB_GEN_DRIVER)     += mub_gen.o
obj-$(CONFIG_MARVELL_PORTM_BOOT_CFG)	+= portm-boot-cfg.o
obj-$(CONFIG_MARVELL_LED_BLINK_RATE)	+= led-blink-rate.o
obj-$(CONFIG_MARVELL_RETIMER_MGMT)	+= retimer-mgmt.o
obj-$(CONFIG_MARVELL_CN10K_RPRAM)	+= rpram.o
obj-$(CONFIG_MARVELL_MEMTEST)		+= memtest.o
obj-$(CONFIG_MARVELL_CN10K_MAC_MGMT)    += mac_mgmt.o
