/*******************************************************************************
Copyright (C) Marvell International Ltd. and its affiliates

This software file (the "File") is owned and distributed by Marvell
International Ltd. and/or its affiliates ("Marvell") under the following
alternative licensing terms.  Once you have made an election to distribute the
File under one of the following license alternatives, please (i) delete this
introductory statement regarding license alternatives, (ii) delete the two
license alternatives that you have not elected to use and (iii) preserve the
Marvell copyright notice above.


********************************************************************************
Marvell GPL License Option

If you received this File from Marvell, you may opt to use, redistribute and/or
modify this File in accordance with the terms and conditions of the General
Public License Version 2, June 1991 (the "GPL License"), a copy of which is
available along with the File in the license.txt file or by writing to the Free
Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 or
on the worldwide web at http://www.gnu.org/licenses/gpl.txt.

THE FILE IS DISTRIBUTED AS-IS, WITHOUT WARRANTY OF ANY KIND, AND THE IMPLIED
WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY
DISCLAIMED.  The GPL License provides additional details about this warranty
disclaimer.
*******************************************************************************/

#include "tm_to_qmtm_enums.h"
#include "tm_errcodes.h"


/*#define CONVERT_ERROR_CODE(code)  if (rc==code) return QM##code;*/
#define CONVERT_ERROR_CODE(code)  if (rc == code) return code;



int	tm_to_qmtm_errcode(int rc)
{
/** HW error codes */
	CONVERT_ERROR_CODE(TM_HW_GEN_CONFIG_FAILED)
	CONVERT_ERROR_CODE(TM_HW_WRED_CURVE_FAILED)
	CONVERT_ERROR_CODE(TM_HW_DROP_PROFILE_FAILED)
	CONVERT_ERROR_CODE(TM_HW_CONF_PER_SCHEME_FAILED)
	CONVERT_ERROR_CODE(TM_HW_TREE_CONFIG_FAIL)
	CONVERT_ERROR_CODE(TM_HW_AGING_CONFIG_FAIL)
	CONVERT_ERROR_CODE(TM_HW_PORT_CONFIG_FAIL)
	CONVERT_ERROR_CODE(TM_HW_C_NODE_CONFIG_FAIL)
	CONVERT_ERROR_CODE(TM_HW_B_NODE_CONFIG_FAIL)
	CONVERT_ERROR_CODE(TM_HW_A_NODE_CONFIG_FAIL)
	CONVERT_ERROR_CODE(TM_HW_QUEUE_CONFIG_FAIL)

	/**< 11 */
	CONVERT_ERROR_CODE(TM_HW_CHANGE_SHAPING_STATUS_FAILED)
	CONVERT_ERROR_CODE(TM_HW_PORT_DWRR_BYTES_PER_BURST_FAILED)
	CONVERT_ERROR_CODE(TM_HW_QMR_GET_ERRORS_FAILED)
	CONVERT_ERROR_CODE(TM_HW_BAP_GET_ERRORS_FAILED)
	CONVERT_ERROR_CODE(TM_HW_RCB_GET_ERRORS_FAILED)
	CONVERT_ERROR_CODE(TM_HW_SCHED_GET_ERRORS_FAILED)
	CONVERT_ERROR_CODE(TM_HW_DROP_GET_ERRORS_FAILED)
	CONVERT_ERROR_CODE(TM_HW_SHAPING_PROF_FAILED)
	CONVERT_ERROR_CODE(TM_HW_READ_PORT_STATUS_FAIL)
	CONVERT_ERROR_CODE(TM_HW_READ_C_NODE_STATUS_FAIL)
	CONVERT_ERROR_CODE(TM_HW_READ_B_NODE_STATUS_FAIL)
	CONVERT_ERROR_CODE(TM_HW_READ_A_NODE_STATUS_FAIL)
	CONVERT_ERROR_CODE(TM_HW_READ_QUEUE_STATUS_FAIL)
	CONVERT_ERROR_CODE(TM_HW_GET_QUEUE_LENGTH_FAIL)
	CONVERT_ERROR_CODE(TM_HW_GET_QMR_PKT_STAT_FAILED)
	CONVERT_ERROR_CODE(TM_HW_GET_RCB_PKT_STAT_FAILED)
	CONVERT_ERROR_CODE(TM_HW_SET_SMS_PORT_ATTR_FAILED)
	CONVERT_ERROR_CODE(TM_HW_ELIG_PRIO_FUNC_FAILED)
	CONVERT_ERROR_CODE(TM_HW_AQM_CONFIG_FAIL)
	CONVERT_ERROR_CODE(TM_HW_COLOR_NUM_CONFIG_FAIL)
	CONVERT_ERROR_CODE(TM_HW_DP_QUERY_RESP_CONF_FAILED)
	CONVERT_ERROR_CODE(TM_HW_QUEUE_COS_CONF_FAILED)
	CONVERT_ERROR_CODE(TM_HW_TM2TM_GLOB_CONF_FAILED)
	CONVERT_ERROR_CODE(TM_HW_TM2TM_CHANNEL_CONF_FAILED)
	CONVERT_ERROR_CODE(TM_HW_TM2TM_LC_CONF_FAILED)
	CONVERT_ERROR_CODE(TM_HW_TM2TM_ENABLE_FAILED)


/** configuration  error codes */
	CONVERT_ERROR_CODE(TM_CONF_INVALID_PROD_NAME)
	CONVERT_ERROR_CODE(TM_CONF_PER_RATE_L_K_N_NOT_FOUND)
	CONVERT_ERROR_CODE(TM_CONF_RES_INC_BW_TS_NOT_FOUND)
	CONVERT_ERROR_CODE(TM_CONF_RES_ACC_NOT_FOUND)
	CONVERT_ERROR_CODE(TM_CONF_NON_RES_ACC_NOT_FOUND)
	CONVERT_ERROR_CODE(TM_CONF_RES_INC_BW_TS_LESS_ONE)
	CONVERT_ERROR_CODE(TM_CONF_BANK_UPD_RATE_NOT_FOUND)
	CONVERT_ERROR_CODE(TM_CONF_UPD_RATE_NOT_FOUND)
	CONVERT_ERROR_CODE(TM_CONF_NON_RES_INC_BW_TS_LESS_ONE)
	CONVERT_ERROR_CODE(TM_CONF_PORT_IND_OOR)
	CONVERT_ERROR_CODE(TM_CONF_PORT_QUANTUM_OOR)
	CONVERT_ERROR_CODE(TM_CONF_PORT_DWRR_PRIO_OOR)
	CONVERT_ERROR_CODE(TM_CONF_P_WRED_PROF_REF_OOR)
	CONVERT_ERROR_CODE(TM_CONF_PORT_BW_OOR)
	CONVERT_ERROR_CODE(TM_CONF_PORT_BS_OOR)
	CONVERT_ERROR_CODE(TM_CONF_Q_SHAPING_PROF_REF_OOR)
	CONVERT_ERROR_CODE(TM_CONF_Q_QUANTUM_OOR)
	CONVERT_ERROR_CODE(TM_CONF_Q_WRED_PROF_REF_OOR)
	CONVERT_ERROR_CODE(TM_CONF_A_NODE_IND_OOR)
	CONVERT_ERROR_CODE(TM_CONF_A_SHAPING_PROF_REF_OOR)
	CONVERT_ERROR_CODE(TM_CONF_A_QUANTUM_OOR)
	CONVERT_ERROR_CODE(TM_CONF_A_DWRR_PRIO_OOR)
	CONVERT_ERROR_CODE(TM_CONF_A_WRED_PROF_REF_OOR)
	CONVERT_ERROR_CODE(TM_CONF_B_NODE_IND_OOR)
	CONVERT_ERROR_CODE(TM_CONF_B_SHAPING_PROF_REF_OOR)
	CONVERT_ERROR_CODE(TM_CONF_B_QUANTUM_OOR)
	CONVERT_ERROR_CODE(TM_CONF_B_DWRR_PRIO_OOR)
	CONVERT_ERROR_CODE(TM_CONF_B_WRED_PROF_REF_OOR)
	CONVERT_ERROR_CODE(TM_CONF_C_NODE_IND_OOR)
	CONVERT_ERROR_CODE(TM_CONF_C_SHAPING_PROF_REF_OOR)
	CONVERT_ERROR_CODE(TM_CONF_C_QUANTUM_OOR)
	CONVERT_ERROR_CODE(TM_CONF_C_DWRR_PRIO_OOR)
	CONVERT_ERROR_CODE(TM_CONF_C_WRED_PROF_REF_OOR)
	CONVERT_ERROR_CODE(TM_CONF_C_WRED_COS_OOR)
	CONVERT_ERROR_CODE(TM_CONF_ELIG_PRIO_FUNC_ID_OOR)
	CONVERT_ERROR_CODE(TM_CONF_DP_COS_SEL_OOR)
	CONVERT_ERROR_CODE(TM_CONF_EXT_HDR_SIZE_OOR)
	CONVERT_ERROR_CODE(TM_CONF_CTRL_PKT_STR_OOR)
	CONVERT_ERROR_CODE(TM_CONF_DELTA_RANGE_OOR)
	CONVERT_ERROR_CODE(TM_CONF_TM2TM_EGR_ELEMS_OOR)
	CONVERT_ERROR_CODE(TM_CONF_TM2TM_SRC_LVL_OOR)
	CONVERT_ERROR_CODE(TM_CONF_TM2TM_BP_LVL_OOR)
	CONVERT_ERROR_CODE(TM_CONF_TM2TM_BP_THRESH_OOR)
	CONVERT_ERROR_CODE(TM_CONF_TM2TM_DP_LVL_OOR)
	CONVERT_ERROR_CODE(TM_CONF_TM2TM_CTRL_HDR_OOR)
	CONVERT_ERROR_CODE(TM_CONF_TM2TM_PORT_FOR_CTRL_PKT_OOR)
	CONVERT_ERROR_CODE(TM_CONF_PORT_SPEED_OOR)
	CONVERT_ERROR_CODE(TM_CONF_PORT_MIN_SHAP_NOT_INC_BW_MULT)
	CONVERT_ERROR_CODE(TM_CONF_PORT_MAX_SHAP_NOT_INC_BW_MULT)
	CONVERT_ERROR_CODE(TM_CONF_PORT_SHAP_MAX_NOT_MULT_MIN)
	CONVERT_ERROR_CODE(TM_CONF_PORT_BW_OUT_OF_SPEED)
	CONVERT_ERROR_CODE(TM_CONF_INVALID_NUM_OF_C_NODES)
	CONVERT_ERROR_CODE(TM_CONF_INVALID_NUM_OF_B_NODES)
	CONVERT_ERROR_CODE(TM_CONF_INVALID_NUM_OF_A_NODES)
	CONVERT_ERROR_CODE(TM_CONF_INVALID_NUM_OF_QUEUES)
	CONVERT_ERROR_CODE(TM_CONF_LVL_MIN_BW_VIOLATION)
	CONVERT_ERROR_CODE(TM_CONF_LVL_MAX_BW_VIOLATION)
	CONVERT_ERROR_CODE(TM_CONF_LVL_MIN_INC_VIOLATION)
	CONVERT_ERROR_CODE(TM_CONF_LVL_MIN_NOT_MULT_INC)
	CONVERT_ERROR_CODE(TM_CONF_LVL_MAX_NOT_MULT_INC)
	CONVERT_ERROR_CODE(TM_CONF_TM2TM_AQM_INVALID_COLOR_NUM)
	CONVERT_ERROR_CODE(TM_CONF_MIN_SHAP_NOT_INC_BW_MULT)
	CONVERT_ERROR_CODE(TM_CONF_MAX_SHAP_NOT_INC_BW_MULT)
	CONVERT_ERROR_CODE(TM_CONF_SHAP_MAX_NOT_MULT_MIN)
	CONVERT_ERROR_CODE(TM_CONF_SHAP_MIN_NOT_MULT_MIN)
	CONVERT_ERROR_CODE(TM_CONF_REORDER_NODES_NOT_ADJECENT)
	CONVERT_ERROR_CODE(TM_CONF_MIN_TOKEN_TOO_LARGE)
	CONVERT_ERROR_CODE(TM_CONF_MAX_TOKEN_TOO_LARGE)
	CONVERT_ERROR_CODE(TM_CONF_PORT_MIN_TOKEN_TOO_LARGE)
	CONVERT_ERROR_CODE(TM_CONF_PORT_MAX_TOKEN_TOO_LARGE)
	CONVERT_ERROR_CODE(TM_CONF_MAX_BW_TS_TOO_LARGE)
	CONVERT_ERROR_CODE(TM_CONF_REORDER_CHILDREN_NOT_AVAIL)
	CONVERT_ERROR_CODE(TM_CONF_PORT_IND_NOT_EXIST)
	CONVERT_ERROR_CODE(TM_CONF_A_NODE_IND_NOT_EXIST)
	CONVERT_ERROR_CODE(TM_CONF_B_NODE_IND_NOT_EXIST)
	CONVERT_ERROR_CODE(TM_CONF_C_NODE_IND_NOT_EXIST)
	CONVERT_ERROR_CODE(TM_CONF_CANNT_GET_LAD_FREQUENCY)
	CONVERT_ERROR_CODE(TM_CONF_UPD_RATE_NOT_CONF_FOR_LEVEL)
	CONVERT_ERROR_CODE(TM_CONF_TM2TM_CHANNEL_NOT_CONFIGURED)
	CONVERT_ERROR_CODE(TM_CONF_PORT_IND_USED)
	CONVERT_ERROR_CODE(TM_CONF_NULL_LOGICAL_NAME)
	CONVERT_ERROR_CODE(TM_CONF_WRONG_LOGICAL_NAME)

	return rc;
}


